-   id: go-fmt
    name: 'go fmt'
    entry: run-go-fmt.sh
    files: '\.go$'
    language: 'script'
    require_serial: true
    description: "Runs `gofmt`, requires golang"
-   id: go-imports
    name: 'go imports'
    entry: run-go-imports.sh
    files: '\.go$'
    language: 'script'
    require_serial: true
    description: "Runs `goimports`, requires golang"
-   id: go-unit-tests
    name: 'go-unit-tests'
    entry: run-go-unit-tests.sh
    files: '\.go$'
    language: 'script'
    pass_filenames: false
    require_serial: true
    description: "Runs `go test`"
-   id: go-build
    name: 'go-build'
    entry: run-go-build.sh
    files: '\.go$'
    language: 'script'
    pass_filenames: false
    require_serial: true
    description: "Runs `go build`, requires golang"
-   id: go-mod-tidy
    name: 'go-mod-tidy'
    entry: run-go-mod-tidy.sh
    files: '\.go$'
    language: 'script'
    pass_filenames: false
    description: "Runs `go mod tidy -v`, requires golang"
-   id: staticcheck
    name: 'staticcheck'
    entry: run-staticcheck.sh
    files: '\.go$'
    language: 'script'
    pass_filenames: false
    description: "Runs `staticcheck`, requires https://staticcheck.io/docs/#installation"
